### ISSUE TITLE
Request to the 40K RefAng data reported in the paper

### ISSUE THREAD

**Issue by shiwk20** [ytyz1307zzh/RefAug#1]
Hi, thanks for your great work. I downloaded your RefAng training data, which contains 14964 lines. And the data size you reported in the paper is 40K. Can you release the original 40K data reported in your paper?

**Comment by ytyz1307zzh** [comment]
Hello,

Thank you for the interest in our work. There may be some misunderstanding here. As mentioned in Section 4.1.1 and Table 16, the standard setting of our work utilized training data from GSM8k and MATH, containing ~15k data in total. Q-Aug and A-Aug augmented one additional example for each training instance, so they have ~30k training data. MetaMath has ~400k training examples, of which ~40k were augmented by us with RefAug. Could you specify which data you are looking for? Thanks!
